# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "2AKDXVmg1/7aWof2Kyp4N8RDs3e1xtw+pd7AoiwPBTBDXVYf9Ayj+CawBqYp0wa5z7DM7udnkL+iJY7CrDnsxW02w5ws3D6KmP1TIVK5ilaB2zyTMNgsjEJLIYx7ZmUTsXD+UKxaGvHywW3fq2VkJ6ePZ0h5eJ4ee3jEXMYCGbVScEd6egmBI0U6mnXZwfrw1wF/QDxvzNFuWim/texP5DKP3fxBd9MMZqu/07T2SUVNjaMyIoc3kR5qO+evwAMvSaI5UW6HzefSexCW+odFQjQVZ2yB24YyE3UFYg/DtYUbYCUxJReDUuW9wx+pWBFr1jkalEykI0sdtc9mgWsoSABoaVCxEJyfFB3UlA821ALh7teXdvGMSxmbapkFLp59v7eXL59wygELu38ZIH/y02v/hW5zZZCwT3ceZ8M5/PSTnOtX+OBG5tNvGJf3O/p974K6hSr1S1J2/glQ/Mz6E/u8NUBgFOXM+KUi/79aJM17MuNkLgV/H7/dIH7CvbIFFT89tA9pDVzFUOPdslSuQ18LX1noQrBNA31XdDv3DKPnJnF5eCvDPpXEY/o2bbpdLzoy4S5CiOhmyS/AWmEccTPFPjXjFQgcyAe3dbcSX/Lib8CSw2keFGdjQd/uPUCDjYchrFCzoa2aFkjqlFGXy6s27Jz4S1i6RFxBZaz404E="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
