travis:
  secure:
    BINSTAR_TOKEN: 2AKDXVmg1/7aWof2Kyp4N8RDs3e1xtw+pd7AoiwPBTBDXVYf9Ayj+CawBqYp0wa5z7DM7udnkL+iJY7CrDnsxW02w5ws3D6KmP1TIVK5ilaB2zyTMNgsjEJLIYx7ZmUTsXD+UKxaGvHywW3fq2VkJ6ePZ0h5eJ4ee3jEXMYCGbVScEd6egmBI0U6mnXZwfrw1wF/QDxvzNFuWim/texP5DKP3fxBd9MMZqu/07T2SUVNjaMyIoc3kR5qO+evwAMvSaI5UW6HzefSexCW+odFQjQVZ2yB24YyE3UFYg/DtYUbYCUxJReDUuW9wx+pWBFr1jkalEykI0sdtc9mgWsoSABoaVCxEJyfFB3UlA821ALh7teXdvGMSxmbapkFLp59v7eXL59wygELu38ZIH/y02v/hW5zZZCwT3ceZ8M5/PSTnOtX+OBG5tNvGJf3O/p974K6hSr1S1J2/glQ/Mz6E/u8NUBgFOXM+KUi/79aJM17MuNkLgV/H7/dIH7CvbIFFT89tA9pDVzFUOPdslSuQ18LX1noQrBNA31XdDv3DKPnJnF5eCvDPpXEY/o2bbpdLzoy4S5CiOhmyS/AWmEccTPFPjXjFQgcyAe3dbcSX/Lib8CSw2keFGdjQd/uPUCDjYchrFCzoa2aFkjqlFGXy6s27Jz4S1i6RFxBZaz404E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
